version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - build:/build
    working_dir: /app
    tty: true
    environment:
      - CARGO_TARGET_DIR=/build/target
      - JWK_URL=${JWK_URL:-https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com}
      - JWK_ISSUER=${JWK_ISSUER}
      - ACCESS_CONTROL_ALLOW_ORIGIN=${ACCESS_CONTROL_ALLOW_ORIGIN:-localhost:3000}
volumes:
  build:
