AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  App:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: app
      Handler: bootstrap.is.real.handler
      Runtime: provided.al2
      MemorySize: 512
      CodeUri: .
      Events:
        Api:
          Type: Api
          Properties:
            Path: "/{proxy+}"
            Method: ANY
      Environment:
        Variables:
          RUST_LOG: info
          RUST_BACKTRACE: 1
          RUST_LOG_STYLE: never
    Metadata:
      BuildMethod: makefile
